### ISSUE TITLE
EtherScandb report format has a design flaw which our script needs to handle.

### ISSUE THREAD

**Issue by VinceICPO** [INTERPOL-Innovation-Centre/TagPackConverters#7]
By default, our script gets the source data from the raw scams.yaml file under https://github.com/MrLuit/EtherScamDB/tree/master/_data

In this file, there is effectively a major misconception since every report is marked as one crypto but actually contains any number of other cryptocurrency addresses... In the below, the report is marked "BTC" when it actually contains many other currencies...
```
    id: 6593
    name: backxcoin.com
    url: 'http://backxcoin.com'
    coin: BTC
    category: Phishing
    subcategory: Malware
    description: 'Hosting a malicious browser extension down (CCB - same as https://medium.com/mycrypto/ef9c10f0128f - see https://twitter.com/sniko_/status/1116123334830374918'
    addresses:
        - '1ADezAfGgKnezVRsujq3yQAADHbvF6e8xc'
        - '0x12A1CCF979D65333E8e27edE047B476736B584a6'
        - 'qzax9ttd75ey5z93m7l6u3urwfuum5nxqufuhxfzcg'
        - 'LU4a7LeMmfDStUE8hCDfTRmyUzyruXPTmH'
        - 'rvVUo33K92NVdUVxhVVhBbo1rArwEDGTW'
        - '0xF38b7Dc84C383AbBd18F2fBF348e0D4Eba9dD61F'
        - 'TWbipjDZHF5Kpm1NB1scznk8uaEP8Qizxd'
    reporter: MyCrypto
```
Our python script needs updating to add a loop using our Regex list to check each address before adding all of them to the TagPack.

Any volunteers to do that ?

_Originally posted by @VinceICPO in https://github.com/graphsense/graphsense-tagpacks/issues/23#issuecomment-1087355084_
